ALTER TABLE gl_qcm_questions
  MODIFY COLUMN photo_url VARCHAR(1024) DEFAULT NULL,
  MODIFY COLUMN photo_url_hd VARCHAR(1024) DEFAULT NULL,
  MODIFY COLUMN photo_description_url VARCHAR(1024) DEFAULT NULL,
  MODIFY COLUMN photo_licence_url VARCHAR(1024) DEFAULT NULL,
  MODIFY COLUMN wikipedia_url VARCHAR(1024) DEFAULT NULL,
  MODIFY COLUMN photo_credit TEXT DEFAULT NULL;
