-- =====================================================================
-- ForetMap — `password_reset_tokens` est polymorphe : pas de clé étrangère
-- vers `users`.
--
-- CONTEXTE. La migration 185 pose `fk_password_reset_user`
-- (`password_reset_tokens.user_id` → `users.id`) pour garantir qu'un jeton ne
-- survive pas au compte qui l'a demandé. L'intention est bonne, mais la table
-- est **polymorphe** : la colonne `user_id` désigne un compte de `users`
-- (`user_type` = 'student' / 'teacher') **ou** un joueur GL de `gl_players`
-- (`user_type` = 'gl_player', cf. `routes/gl/auth.js` →
-- `createPasswordResetToken('gl_player', player.id)`).
--
-- Conséquence : depuis la 185, « mot de passe oublié » échoue pour un joueur GL —
-- l'INSERT du jeton viole la contrainte (`ER_NO_REFERENCED_ROW_2`). Le test
-- `tests/gl-auth-forgot-password.test.js` le montre, rouge sur `main`.
--
-- Une clé étrangère ne peut pas exprimer « existe dans users OU dans gl_players » ;
-- on la retire donc. Ce que la 185 voulait garantir reste couvert :
--   * `lib/studentDeletion.js` purge les jetons du compte supprimé ;
--   * les jetons expirent (TTL) et sont marqués consommés à l'usage ;
--   * l'index `user_id` posé par la 185 est conservé (il sert les purges).
-- La clé étrangère de `user_roles`, elle, est **conservée** : cette table ne
-- désigne que des comptes de `users` (`user_type` ∈ student/teacher).
--
-- Idempotent : le DROP rejoué renvoie l'errno 1091, ignoré par le runner.
-- =====================================================================

ALTER TABLE password_reset_tokens DROP FOREIGN KEY fk_password_reset_user;
