-- QCM de raisonnement (slugs existants uniquement).
-- INSERT IGNORE. Codes QF91xx / GQCM91xx. Liaisons via le modèle unifié.
-- Bonne réponse en A acceptée (mélange runtime). Aucun ALTER.

INSERT IGNORE INTO gl_qcm_categories (slug, nom, emoji, order_index, created_at, updated_at) VALUES
  ('faune', 'Faune', '🦊', 10, NOW(), NOW()),
  ('flore', 'Flore', '🌿', 20, NOW(), NOW()),
  ('ecosystemes', 'Écosystèmes', '🕸️', 30, NOW(), NOW()),
  ('biome', 'Biome', '🗺️', 40, NOW(), NOW()),
  ('geologie', 'Géologie', '🪨', 50, NOW(), NOW()),
  ('perturbations', 'Perturbations', '⚡', 60, NOW(), NOW());

INSERT IGNORE INTO quiz_questions
(question_code, categorie_slug, numero_dans_categorie, question,
 choix_a, choix_b, choix_c, choix_d, choix_e,
 reponse_correcte, reponse_texte, niveau, difficulte, difficulte_label,
 feedback_correct, feedback_a, feedback_b, feedback_c, feedback_d, feedback_e,
 notes_pedagogiques, tags, statut, created_at, updated_at)
VALUES
('QF9101','ecologie_reseaux',9101,
 'Pourquoi un réseau trophique décrit-il mieux un jardin qu’une seule chaîne alimentaire ?',
 'Parce que plusieurs espèces partagent souvent les mêmes ressources et ont plusieurs prédateurs',
 'Parce qu’une chaîne alimentaire est toujours fausse',
 'Parce que les décomposeurs n’entrent jamais dans un réseau',
 'Parce que l’énergie augmente à chaque transfert',
 NULL,'A','Plusieurs espèces partagent souvent les mêmes ressources et ont plusieurs prédateurs',
 'college',2,'⭐⭐ Moyen',
 'Un réseau relie plusieurs chaînes : une même plante peut nourrir plusieurs herbivores, eux-mêmes chassés par plusieurs prédateurs.',
 'Oui : les relations alimentaires se croisent, ce n’est pas une file unique.',
 'Non. Une chaîne reste un extrait utile, mais trop simple pour le jardin entier.',
 'Non. Les décomposeurs font partie du réseau, notamment via la matière morte.',
 'Non. L’énergie disponible diminue généralement à chaque transfert.',
 NULL,'Raisonne sur la différence chaîne / réseau.','reseau, chaine, ecologie','actif',NOW(),NOW()),
('QF9102','ecologie_reseaux',9102,
 'Un renard mange une carcasse. Quelle formulation est la plus juste ?',
 'Il agit surtout en nécrophage : il consomme de la matière animale déjà morte',
 'Il décompose la carcasse comme un champignon',
 'Il nitrifie le sol en oxydant l’ammonium',
 'Il pollinise les plantes voisines',
 NULL,'A','Il agit surtout en nécrophage : il consomme de la matière animale déjà morte',
 'college',2,'⭐⭐ Moyen',
 'Manger une carcasse n’est pas la même chose que minéraliser la matière comme le font champignons et microorganismes.',
 'Oui. La nécrophagie est une consommation de cadavres, distincte de la décomposition microbienne.',
 'Non. Les champignons et beaucoup de bactéries dégradent la matière ; le renard l’ingère.',
 'Non. La nitrification est une oxydation microbienne de l’azote.',
 'Non. Cela n’a aucun rapport avec la pollinisation.',
 NULL,'Distingue nécrophagie et décomposeurs.','necrophagie, decomposeur','actif',NOW(),NOW()),
('QF9103','cycle_azote_aquaponie',9103,
 'Dans le cycle de l’azote, que transforme principalement la nitrification ?',
 'L’ammonium en nitrite puis souvent en nitrate',
 'Le diazote atmosphérique directement en protéines',
 'Les nitrates exclusivement en ammoniac toxique',
 'L’eau en dioxygène pour les poissons',
 NULL,'A','L’ammonium en nitrite puis souvent en nitrate',
 'lycee',2,'⭐⭐ Moyen',
 'La nitrification oxyde l’ammonium. Le nitrate n’est pas une fin unique : il peut être assimilé, lessivé ou dénitrifié.',
 'Oui. Ce sont les deux étapes classiques (parfois réunies chez certains microbes).',
 'Non. La fixation de N2 est un autre processus, réalisé par d’autres organismes.',
 'Non. Les nitrates ne se transforment pas « exclusivement » en ammoniac toxique.',
 'Non. La nitrification ne produit pas l’oxygène respiré par les poissons.',
 NULL,'Évite le nitrate comme produit final universel.','nitrification, azote','actif',NOW(),NOW()),
('QF9104','cycle_azote_aquaponie',9104,
 'Pourquoi ne pas dire que « tout l’ammonium est toxique pour les poissons » ?',
 'Parce que NH4+ et NH3 sont en équilibre : la forme NH3, plus toxique, augmente surtout avec le pH et la température',
 'Parce que l’ammonium n’existe jamais dans l’eau',
 'Parce que les poissons n’excrètent aucun déchet azoté',
 'Parce que le nitrate est toujours plus toxique que NH3',
 NULL,'A','NH4+ et NH3 sont en équilibre ; NH3 augmente avec pH et température',
 'lycee',2,'⭐⭐ Moyen',
 'La toxicité dépend surtout de la fraction NH3, liée au pH et à la température.',
 'Oui. Distinguer les deux formes évite un raccourci dangereux en aquaponie.',
 'Non. L’ammonium est courant dans les bassins.',
 'Non. Les poissons excrètent bien des déchets azotés.',
 'Non. La comparaison n’est pas aussi simple, et ce n’est pas le point.',
 NULL,'Couple ammonium/ammoniac.','ammonium, ammoniac, pH','actif',NOW(),NOW()),
('QF9105','sol_compost',9105,
 'Quel rôle distingue le mieux un ver de terre d’un champignon décomposeur ?',
 'Le ver ingère et fragmente la litière (détritivore) ; le champignon dégrade chimiquement la matière morte',
 'Le ver oxyde l’ammonium en nitrate',
 'Le champignon chasse les vers',
 'Les deux fabriquent de l’ATP pour le stocker tout l’hiver',
 NULL,'A','Le ver est détritivore ; le champignon dégrade chimiquement la matière',
 'college',2,'⭐⭐ Moyen',
 'Détritivores et décomposeurs coopèrent souvent, mais ce n’est pas le même métier écologique.',
 'Oui. Fragmenter n’est pas synonyme de minéraliser.',
 'Non. La nitrification est microbienne.',
 'Non. Ce n’est pas une relation de prédation typique du compost.',
 'Non. L’ATP n’est pas un stock hivernal.',
 NULL,'détritivore ≠ décomposeur.','lombric, champignon, compost','actif',NOW(),NOW()),
('QF9106','energie_matiere',9106,
 'Pourquoi l’énergie disponible diminue-t-elle généralement d’un niveau trophique au suivant ?',
 'Parce qu’une grande part est dissipée en chaleur lors du métabolisme',
 'Parce que la matière disparaît définitivement à chaque repas',
 'Parce que les plantes recréent l’énergie chimique à partir de rien',
 'Parce que la règle des 10 % est une constante physique universelle',
 NULL,'A','Une grande part est dissipée en chaleur lors du métabolisme',
 'lycee',2,'⭐⭐ Moyen',
 'La matière circule et se recycle ; l’énergie, elle, se dissipe. La règle des 10 % reste une approximation pédagogique.',
 'Oui. Respiration et activité transforment beaucoup d’énergie en chaleur.',
 'Non. Les atomes de la matière sont réorganisés, pas annihilés.',
 'Non. Les plantes convertissent l’énergie lumineuse, elles ne la créent pas « à partir de rien ».',
 'Non. 10 % est un ordre de grandeur utile, pas une loi universelle.',
 NULL,'Séparer flux d’énergie et cycles de matière.','energie, pyramide, chaleur','actif',NOW(),NOW()),
('QF9107','evolution_biodiversite',9107,
 'La biodiversité se décrit à plusieurs échelles. Laquelle manque si on ne compte que le nombre d’espèces ?',
 'La diversité génétique dans les populations et la diversité des écosystèmes',
 'Uniquement le nombre de prédateurs',
 'Uniquement la couleur des fleurs',
 'Le nom français des plantes',
 NULL,'A','La diversité génétique et celle des écosystèmes',
 'college',2,'⭐⭐ Moyen',
 'Compter les espèces est utile, mais incomplet : gènes et milieux comptent aussi.',
 'Oui. Trois niveaux classiques : gènes, espèces, écosystèmes.',
 'Non. Ce n’est qu’une tranche du réseau.',
 'Non. Un trait visible ne mesure pas la biodiversité.',
 'Non. Le nom vernaculaire n’est pas une échelle de diversité.',
 NULL,'Trois niveaux, sans garantie contre tout ravageur.','biodiversite, genes','actif',NOW(),NOW()),
('QF9108','populations_equilibres',9108,
 'Après une tempête, une haie se recompose en quelques années. De quoi parle-t-on surtout ?',
 'De résilience : le milieu retrouve une partie de ses fonctions après la perturbation',
 'De résistance uniquement : rien n’a bougé pendant la tempête',
 'De dérive génétique chez les oiseaux migrateurs',
 'D’une nitrification arrêtée à jamais',
 NULL,'A','De résilience : retour partiel des fonctions après perturbation',
 'lycee',2,'⭐⭐ Moyen',
 'La résilience n’exige pas un retour identique à l’état initial ; la résistance décrit plutôt la faible variation pendant le choc.',
 'Oui. On regarde la capacité à se rétablir, pas l’immobilité pendant la tempête.',
 'Non. Si rien n’avait bougé, ce serait plutôt de la résistance.',
 'Non. La dérive concerne les fréquences d’allèles, surtout dans les petites populations.',
 'Non. Un choc n’arrête pas « à jamais » le cycle de l’azote.',
 NULL,'Résilience ≠ résistance.','resilience, perturbation','actif',NOW(),NOW()),
('QF9109','plantes_biologie',9109,
 'Une légumineuse enrichit le sol en azote. Quelle lecture est la plus prudente ?',
 'Des bactéries associées peuvent fixer N2 ; ce n’est pas la plante seule qui « fabrique l’azote »',
 'La plante oxyde l’ammonium en nitrate dans ses feuilles',
 'La plante transforme le nitrate en diazote atmosphérique',
 'Toute légumineuse empêche toute carence azotée au jardin',
 NULL,'A','Des bactéries associées peuvent fixer N2',
 'lycee',2,'⭐⭐ Moyen',
 'La fixation biologique est un partenariat microbien.',
 'Oui. Le genre et les rhizobiums comptent autant que le nom « légumineuse ».',
 'Non. La nitrification se fait surtout dans le sol, par des microbes.',
 'Non. C’est plutôt le sens de la dénitrification, un autre processus.',
 'Non. Aucune plante ne garantit à elle seule l’absence de carence.',
 NULL,'Évite le mythe « le trèfle suffit toujours ».','legumineuse, fixation, azote','actif',NOW(),NOW());

INSERT IGNORE INTO resource_question_links
  (resource_type, resource_ref, question_code, origin, status, is_gating)
VALUES
  ('glossary','FM0010','QF9101','import','approved',0),
  ('glossary','FM0012','QF9101','import','approved',0),
  ('glossary','FM0015','QF9102','import','approved',0),
  ('glossary','FM0021','QF9103','import','approved',0),
  ('glossary','FM0023','QF9103','import','approved',0),
  ('glossary','FM0022','QF9104','import','approved',0),
  ('glossary','FM0015','QF9105','import','approved',0),
  ('glossary','FM0204','QF9106','import','approved',0),
  ('glossary','FM0002','QF9107','import','approved',0),
  ('glossary','FM0229','QF9108','import','approved',0),
  ('glossary','FM0020','QF9109','import','approved',0);

INSERT IGNORE INTO gl_qcm_questions
(question_code, biome_slug, categorie_slug, numero_dans_categorie, question,
 choix_a, choix_b, choix_c, choix_d, choix_e,
 reponse_correcte, reponse_texte, niveau, difficulte, difficulte_label,
 feedback_correct, feedback_a, feedback_b, feedback_c, feedback_d, feedback_e,
 notes_pedagogiques, tags, statut, created_at, updated_at)
VALUES
('GQCM9101','toundra','faune',9101,
 'Le lièvre arctique passe l’hiver sur la toundra. Quelle affirmation est la plus juste ?',
 'Il reste généralement actif ; le présenter comme hibernant est inexact',
 'Il hiberne forcément tout l’hiver comme une marmotte',
 'Il n’existe que dans les forêts tropicales',
 'Il fixe l’azote atmosphérique',
 'Il est un décomposeur de la neige',
 'A','Il reste généralement actif ; le présenter comme hibernant est inexact',
 'cycle 4',2,'⭐⭐ Moyen',
 'Rester actif en hiver, avec un pelage et des pattes adaptés, n’est pas de l’hibernation.',
 'Oui. L’anecdote « il hiberne » est un raccourci à éviter.',
 'Non. L’hibernation n’est pas le mode de vie de ce lièvre.',
 'Non. C’est une espèce des milieux froids.',
 'Non. La fixation de N2 est microbienne, souvent associée à des plantes.',
 'Non. La neige n’est pas « décomposée » par un lièvre.',
 'Niveau collège.','lievre, toundra, hiver','actif',NOW(),NOW()),
('GQCM9102','sahara','flore',9102,
 'Sur une fiche, le nom scientifique « Tamarix » apparaît seul. Que faut-il en conclure ?',
 'On est au rang du genre ; sans épithète, on précise plutôt Tamarix sp.',
 'C’est forcément une espèce unique endémique du Sahara',
 'C’est le nom d’une famille animale',
 'Un genre ne peut pas être utilisé en sciences',
 'Cela prouve que la plante hiberne',
 'A','On est au rang du genre ; on écrit Tamarix sp. si l’espèce n’est pas identifiée',
 'lycee',2,'⭐⭐ Moyen',
 'Un seul mot capitalisé désigne en général un genre, pas une espèce précise.',
 'Oui. Le « sp. » signale que l’espèce n’est pas tranchée.',
 'Non. Plusieurs espèces de tamaris existent, et l’endémisme n’est pas automatique.',
 'Non. Tamarix est un genre de plantes.',
 'Non. Le genre est une unité taxonomique valide.',
 'Non. Aucun lien avec l’hibernation.',
 'Aligne SP0015.','tamarix, genre, taxonomie','actif',NOW(),NOW()),
('GQCM9103','savane','ecosystemes',9103,
 'Dans une savane, antilopes, acacias et lions sont reliés. Que représente le mieux un réseau trophique ?',
 'Plusieurs relations alimentaires qui se croisent, pas une seule file d’espèces',
 'Uniquement le climat du biome',
 'La liste des roches du sous-sol',
 'Le fait qu’aucune espèce n’a plus d’une proie',
 'Un schéma où l’énergie augmente à chaque repas',
 'A','Plusieurs relations alimentaires qui se croisent',
 'cycle 4',2,'⭐⭐ Moyen',
 'Le réseau montre que les régimes se recoupent. Une chaîne isolée reste un extrait.',
 'Oui. C’est la définition utile en classe.',
 'Non. Le climat aide à définir le biome, pas le réseau alimentaire.',
 'Non. Cela relève plutôt de la géologie.',
 'Non. Beaucoup d’espèces ont plusieurs proies ou prédateurs.',
 'Non. L’énergie disponible diminue généralement à chaque transfert.',
 'Relie GL9005.','reseau, savane, chaine','actif',NOW(),NOW()),
('GQCM9104','foret_mediterraneenne','biome',9104,
 'Pourquoi un biome n’est-il pas simplement un autre nom pour « écosystème » ?',
 'Un biome est une grande unité climatique et de végétation ; un écosystème est un système d’interactions plus local',
 'Les deux mots sont toujours strictement synonymes',
 'Un biome ne contient jamais d’êtres vivants',
 'Un écosystème n’existe que dans les déserts',
 'Les biomes sont des pays politiques',
 'A','Le biome est une grande unité ; l’écosystème est plus local et relationnel',
 'cycle 4',2,'⭐⭐ Moyen',
 'Les limites de biomes dépendent des classifications.',
 'Oui. L’échelle et le critère changent.',
 'Non. On les emploie parfois l’un pour l’autre dans le langage courant, pas en SVT.',
 'Non. Un biome est défini aussi par le vivant.',
 'Non. Les écosystèmes existent dans tous les milieux.',
 'Non. Un biome n’est pas une frontière administrative.',
 'Terme biome.','biome, ecosysteme','actif',NOW(),NOW()),
('GQCM9105','desert_froid','geologie',9105,
 'Dans un désert froid, le sol et le climat limitent la vie. Quelle lecture est la plus juste ?',
 'Les facteurs abiotiques (froid, eau rare, vent) pèsent autant que les relations entre organismes',
 'Seul le réseau alimentaire compte, le climat n’a aucun effet',
 'Les roches produisent directement les protéines des animaux',
 'Il n’existe aucune variation de température dans un désert',
 'Tous les organismes y hibernent obligatoirement',
 'A','Les facteurs abiotiques pèsent autant que les relations biotiques',
 'cycle 4',2,'⭐⭐ Moyen',
 'L’environnement d’un organisme mêle milieu physique et autres êtres vivants.',
 'Oui. Température, eau et vent structurent qui peut vivre là.',
 'Non. Un réseau alimentaire s’inscrit dans un milieu.',
 'Non. Les roches ne synthétisent pas les protéines.',
 'Non. Les écarts thermiques y sont souvent très forts.',
 'Non. L’hibernation n’est pas une règle universelle.',
 'S’appuie sur GL0084.','abiotique, desert, climat','actif',NOW(),NOW()),
('GQCM9106','taiga','perturbations',9106,
 'Un incendie ouvre une clairière en taïga. Parler de résilience, c’est dire surtout que…',
 'Le milieu peut retrouver une partie de ses fonctions, sans revenir forcément à l’état d’avant',
 'Aucune plante ne reviendra jamais',
 'La dérive génétique explique à elle seule le feu',
 'Toutes les espèces de taïga sont exotiques envahissantes',
 'Le feu crée de l’énergie chimique pour les arbres',
 'A','Le milieu peut retrouver une partie de ses fonctions',
 'lycee',3,'⭐⭐⭐ Difficile',
 'La résilience dépend du système et de la perturbation. Elle ne promet pas une copie conforme de la forêt d’origine.',
 'Oui. Retour de fonctions, pas forcément de la même composition.',
 'Non. La recolonisation est fréquente, à des rythmes variables.',
 'Non. La dérive concerne les allèles, pas la cause du feu.',
 'Non. « Envahissante » suppose introduction + impacts, pas les espèces natives.',
 'Non. Le feu dissipe de l’énergie ; il ne la crée pas pour la photosynthèse.',
 'Niveau lycée, pas 6ème.','resilience, incendie, taiga','actif',NOW(),NOW()),
('GQCM9107','jungle_afc','flore',9107,
 'Une liane tropicale est surnommée « liane à eau ». Que faut-il en conclure pour la boire ?',
 'Le nom vernaculaire ne garantit ni l’espèce ni la potabilité ; il faut rester prudent',
 'Toute liane de jungle donne une eau sûre sans traitement',
 'C’est forcément un castor d’Afrique centrale',
 'Cette plante hiberne sous la canopée',
 'Elle nitrifie à elle seule toute la rivière',
 'A','Le nom vernaculaire ne garantit ni l’espèce ni la potabilité',
 'cycle 4',2,'⭐⭐ Moyen',
 'Un surnom local n’est pas une analyse d’eau.',
 'Oui. Identification et prudence sanitaire d’abord.',
 'Non. Aucune garantie automatique.',
 'Non. Le castor n’est pas une espèce de jungle d’Afrique centrale.',
 'Non. L’hibernation n’est pas le sujet.',
 'Non. La nitrification est microbienne.',
 'Exclut le hors-sujet castor / jungle.','liane, potabilite, jungle','actif',NOW(),NOW()),
('GQCM9108','taiga','faune',9108,
 'La zibeline vit dans les forêts froides d’Eurasie. Quelle phrase évite un raccourci ?',
 'Elle est largement répartie au nord de l’Eurasie ; « endémique de Sibérie » et « hibernante » sont trop forts',
 'Elle n’existe qu’en Sibérie et hiberne tout l’hiver',
 'C’est un poisson des mangroves',
 'Elle invente la dérive génétique à chaque génération',
 'Elle est une plante du Sahara',
 'A','Répartition eurasienne large ; ni strictement endémique de Sibérie, ni hibernante',
 'cycle 4',2,'⭐⭐ Moyen',
 'Une aire vaste n’est pas un endémisme strict. Rester actif l’hiver n’est pas hibernar.',
 'Oui. On corrige deux erreurs fréquentes de fiche.',
 'Non. L’aire dépasse un seul pays, et l’hibernation n’est pas le trait à retenir.',
 'Non. C’est un mammifère forestier.',
 'Non. La dérive est un processus populationnel, pas une invention individuelle.',
 'Non. Ni plante, ni désert chaud.',
 'Aligne SP0146.','zibeline, taiga, endemisme','actif',NOW(),NOW());

INSERT IGNORE INTO gl_resource_question_links
  (question_dataset, resource_type, resource_ref, question_code, origin, status, is_gating)
VALUES
  ('qcm','glossary','GL9005','GQCM9103','import','approved',0),
  ('qcm','glossary','GL9006','GQCM9103','import','approved',0),
  ('qcm','glossary','GL9001','GQCM9101','import','approved',0),
  ('qcm','glossary','GL0084','GQCM9105','import','approved',0),
  ('qcm','glossary','GL9009','GQCM9106','import','approved',0),
  ('qcm','glossary','GL9010','GQCM9106','import','approved',0),
  ('qcm','species','SP0051','GQCM9101','import','approved',0),
  ('qcm','species','SP0015','GQCM9102','import','approved',0),
  ('qcm','species','SP0043','GQCM9107','import','approved',0),
  ('qcm','species','SP0146','GQCM9108','import','approved',0);
