export {
  MARKER_QUESTION_EVENT_TYPES,
  MARKER_QUESTION_RETRIGGER_MODES,
  MARKER_EVENT_TYPES,
  DEFAULT_QUESTION_POOL,
  DEFAULT_QUESTION_CONFIG,
  normalizeStringList,
  normalizeQuestionCode,
  normalizeQuestionPool,
  normalizeQuestionConfig,
  normalizeEventConfig,
  defaultEventConfigForQuestion,
  migrateLegacyMarkerQcmConfig,
  resolveMarkerEventConfig,
  isQuestionMarker,
  eventConfigToLegacyMirror,
  serializeEventConfig,
  parseEventConfigJson,
  normalizeMarkerQuestionRetrigger,
  resolveBiomeSlugsForPool,
} from '../shared/glMarkerEventConfigCore.js';
